#!/bin/zsh

function install_essential_packages {
  APTFILE="$PWD/devops/development/ubuntu/Aptfile"
  sudo apt update
  sudo apt install -y $(awk '!/^ *#/ && NF > 0' "$APTFILE")
}

function install_git_hooks {
  overcommit --install
  overcommit --sign pre-commit
}
