name: CI
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  rubocop:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.3.0"
          bundler-cache: true
      - name: Install dependencies
        run: bundle install
      - name: Analyze code
        run: bundle exec standardrb .
  rspec:
    runs-on: ubuntu-22.04
    env:
      APP_ENV: test
      CI: true
      RACK_ENV: test
      RAILS_ENV: test
    services:
      postgres:
        image: postgres:16.1
        ports: ["5432:5432"]
        env:
          POSTGRES_USER: postgres
          POSTGRES_HOST_AUTH_METHOD: trust
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
    steps:
      - uses: actions/checkout@v3
      - name: Install postgres client dependencies
        run: sudo apt-get install libpq-dev
      - name: Copy env file
        run: cp ./lib/templates/.env.test.template .env.test
      - name: Load .env.test file
        uses: xom9ikk/dotenv@v2
        with:
          path: ./
          mode: test
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.3.0"
          bundler-cache: true
      - name: Create database and running migrations
        run: |
          bundle exec rake auction_fun_core:db:create_database[postgres]
          bundle exec rake auction_fun_core:db:migrate
      - name: Run lint
        run: bundle exec standardrb
      - name: Run suite
        run: bundle exec rspec --color --format progress
